---

- name: Set endpoints and variables for {{ dns_zone.name }}
  ansible.builtin.set_fact:
    fad_api_endpoint_dns_zone_a_aaaa_record: "https://{{ ansible_host }}/api/global_dns_server_zone_child_a_aaaa_record?vdom={{ fad_vdom }}&pkey=fqdn_generate_{{ dns_zone.name }}.&mkey={{ a_aaaa_record.id }}"
    fad_dns_zone_a_aaaa_record_name: "{{ a_aaaa_record.hostname }}.{{ dns_zone.name }}"
    fad_dns_zone_a_aaaa_record_request_body: |
      {
        "mkey": "{{ a_aaaa_record.id }}",
        "hostname": "{{ a_aaaa_record.hostname }}",
        "ip": "{{ a_aaaa_record.ipv4 | default('0.0.0.0') }}",
        "ip6": "{{ a_aaaa_record.ipv6 | default('::') }}",
        "ttl": "{{ a_aaaa_record.ttl | default('-1') }}",
        "source_type": "{{ a_aaaa_record.ip_type | default('ipv4') }}"
      }
  tags:
    - fad_dns_zones
    - fad_dns_zone_a_aaaa_records

- name: Check if the A or AAAA Record is exist for domain {{ fad_dns_zone_a_aaaa_record_name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_dns_zone_a_aaaa_record }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_dns_zone_a_aaaa_record_existing_data
  tags:
    - fad_dns_zones
    - fad_dns_zone_a_aaaa_records

- name: Print out the existing A or AAAA Record value for domain {{ fad_dns_zone_a_aaaa_record_name }}
  ansible.builtin.debug:
    var:  fad_dns_zone_a_aaaa_record_existing_data.json.payload
  when: fad_dns_zone_a_aaaa_record_existing_data.json.payload is defined
  tags:
  - fad_dns_zones
  - debug
  - fad_dns_zone_a_aaaa_records

- name: Create new A or AAAA Record if it doesn't exist for domain {{ fad_dns_zone_a_aaaa_record_name }}
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_api_endpoint_dns_zone_a_aaaa_record }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_dns_zone_a_aaaa_record_request_body }}"
  register: fad_dns_zone_a_aaaa_record_post_result
  when: fad_dns_zone_a_aaaa_record_existing_data.json.payload.mkey is undefined
  changed_when: fad_dns_zone_a_aaaa_record_post_result.json.payload == 0
  failed_when: (fad_dns_zone_a_aaaa_record_post_result.json.payload != 0) and (fad_dns_zone_a_aaaa_record_post_result.json.payload != -15)
  tags:
    - fad_dns_zones
    - fad_dns_zone_a_aaaa_records

- name: Update A or AAAA Record if it fail idempotent check for domain {{ fad_dns_zone_a_aaaa_record_name }}
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_api_endpoint_dns_zone_a_aaaa_record }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_dns_zone_a_aaaa_record_request_body }}"
  register: fad_dns_zone_a_aaaa_record_post_result
  when: >
    (fad_dns_zone_a_aaaa_record_existing_data.json.payload.mkey is defined) and
    (fad_dns_zone_a_aaaa_record_existing_data.json.payload.hostname != a_aaaa_record.hostname or
    fad_dns_zone_a_aaaa_record_existing_data.json.payload.ip != a_aaaa_record.ipv4 | default('0.0.0.0') | string or
    fad_dns_zone_a_aaaa_record_existing_data.json.payload.ip6 != a_aaaa_record.ipv6 | default('::') | string or
    fad_dns_zone_a_aaaa_record_existing_data.json.payload.ttl != a_aaaa_record.ttl | default('-1') | string or
    fad_dns_zone_a_aaaa_record_existing_data.json.payload.source_type != a_aaaa_record.ip_type | default('ipv4')
    )
  changed_when: fad_dns_zone_a_aaaa_record_post_result.json.payload == 0
  failed_when: (fad_dns_zone_a_aaaa_record_post_result.json.payload != 0) and (fad_dns_zone_a_aaaa_record_post_result.json.payload != -15)
  tags:
    - fad_dns_zones
    - fad_dns_zone_a_aaaa_records

- name: Check if the A or AAAA Record data has changed for domain {{ fad_dns_zone_a_aaaa_record_name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_dns_zone_a_aaaa_record }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_dns_zone_a_aaaa_record_new_data
  changed_when: fad_dns_zone_a_aaaa_record_new_data.json.payload != fad_dns_zone_a_aaaa_record_existing_data.json.payload
  tags:
    - fad_dns_zones
    - fad_dns_zone_a_aaaa_records
    - debug

- name: Print out the new A or AAAA Record value for domain {{ fad_dns_zone_a_aaaa_record_name }}
  ansible.builtin.debug:
    var:  fad_dns_zone_a_aaaa_record_new_data.json.payload
  tags:
  - fad_dns_zones
  - fad_dns_zone_a_aaaa_records
  - debug
