- name: Add a NS Record DNS for {{ item.hostname }}.{{ item.domain_name }} in {{ item.domain_name }} zone.
  ansible.builtin.uri:
    method: POST
    url: "https://{{ ansible_host }}/api/global_dns_server_zone_child_ns_record?vdom={{ fad_vdom }}&pkey=fqdn_generate_{{ item.domain_name }}."
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
    body: |
      {
        "host_name": "{{ item.hostname }}",
        "domain_name": "@",
        "ip": "{{ item.ip }}",
        "mkey": "{{ item.mkey }}"
      }
  register: glb_host_data
  delegate_to: localhost
  changed_when: "glb_host_data.json.payload == 0"
  failed_when: "glb_host_data.json.payload != -15 and glb_host_data.json.payload != 0"