- name: Add some basic DNS zone entries.
  ansible.builtin.uri:
    method: POST
    url: "https://{{ ansible_host }}/api/global_dns_server_zone_child_a_aaaa_record?vdom={{ fad_vdom }}&pkey=fqdn_generate_{{ item.name }}
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
    body: |
      {
        "hostname": "{{ hostname }}",
        "ip": "{{ ip }}",
        "mkey": "{{ mkey }}",
        "source_type": "{{ source_type }}",
        "ttl": "{{ ttl }}"
      }
  register: glb_host_data
  delegate_to: localhost
  loop: "{{ fad_domains.aaa_entries }}"
  when: "'fortiadc' in group_names"
  changed_when: "glb_host_data.json.payload == 0"
  