---

- name: Print out the DNS Zone CNAME Record existing values.
  ansible.builtin.debug:
    msg: >
      {{ (lookup('url', fad_dns_zone_cname_record_api_endpoint
      % (('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id), validate_certs=false, split_lines=false,
      headers=fad_api_header) | from_json).get('payload') }}
  loop: "{{ fad_dns_zones | subelements('cname_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.alias + '.' + dns_zone.0.name }}"
  tags: [debug]
  when:
    - dns_zone.1 is defined

- name: Create new DNS Zone CNAME Record entry if it's not found.
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_dns_zone_cname_record_api_endpoint | format(('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id) }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: |
      {
        "mkey": "{{ dns_zone.1.id | string }}",
        "alias": "{{ dns_zone.1.alias | string }}",
        "target": "{{ dns_zone.1.target | string }}",
        "ttl": "{{ dns_zone.1.ttl | default('-1') | string }}"
      }
  register: fad_dns_zone_cname_record_post_results
  loop: "{{ fad_dns_zones | subelements('cname_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.alias + '.' + dns_zone.0.name }}"
  when:
    - dns_zone.0.cname_records is defined
    - (lookup('url', fad_dns_zone_cname_record_api_endpoint
      % (('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').mkey is undefined
  changed_when: "fad_dns_zone_cname_record_post_results.json.payload == 0"
  failed_when: "fad_dns_zone_cname_record_post_results.json.payload not in [0, -15]"

- name: Update DNS Zone CNAME Record entry if it's exist and any of its value is changed.
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_dns_zone_cname_record_api_endpoint | format(('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id) }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: |
      {
        "mkey": "{{ dns_zone.1.id | string }}",
        "alias": "{{ dns_zone.1.alias | string }}",
        "target": "{{ dns_zone.1.target | string }}",
        "ttl": "{{ dns_zone.1.ttl | default('-1') | string }}"
      }
  register: fad_dns_zone_cname_record_put_results
  loop: "{{ fad_dns_zones | subelements('cname_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.alias + '.' + dns_zone.0.name }}"
  when: >
    ((lookup('url', fad_dns_zone_cname_record_api_endpoint
      % (('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').mkey is defined) and
    (
    (lookup('url', fad_dns_zone_cname_record_api_endpoint
      % (('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').alias != dns_zone.1.alias or
    (lookup('url', fad_dns_zone_cname_record_api_endpoint
      % (('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').target != dns_zone.1.target or
    (lookup('url', fad_dns_zone_cname_record_api_endpoint
      % (('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').ttl != dns_zone.1.ttl | default('-1') | string
    )
  changed_when: "fad_dns_zone_cname_record_put_results.json.payload == 0"
  failed_when: "fad_dns_zone_cname_record_put_results.json.payload not in [0, -15]"

- name: Print out the DNS Zone CNAME Record values after create/update task.
  ansible.builtin.debug:
    msg: >
      {{ (lookup('url', fad_dns_zone_cname_record_api_endpoint
      % (('fqdn_generate_' + dns_zone.0.name + '.'), dns_zone.1.id), validate_certs=false, split_lines=false,
      headers=fad_api_header) | from_json).get('payload') }}
  loop: "{{ fad_dns_zones | subelements('cname_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.alias + '.' + dns_zone.0.name }}"
  tags: [debug]
  when:
    - dns_zone.0.cname_records is defined
