---

- name: Print out the DNS Zone CAA Record existing values.
  ansible.builtin.debug:
    msg: >
      {{ (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id), validate_certs=false, split_lines=false,
      headers=fad_api_header) | from_json).get('payload') }}
  loop: "{{ fad_dns_zones | subelements('caa_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.value + ' for ' + dns_zone.1.tag + 'for' + dns_zone.0.name }}"
  tags: [debug]

- name: Create new DNS Zone CAA Record entry if it's not found.
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_dns_zone_caa_record_api_endpoint | format((dns_zone.0.name), dns_zone.1.id) }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: |
      {
        "mkey": "{{ dns_zone.1.id | string }}",
        "flag": "{{ dns_zone.1.flag | default('0') | string }}",
        "hostname": "{{ dns_zone.1.hostname | default('@') |string }}",
        "tag": "{{ dns_zone.1.tag | default('issuewild') | string }}",
        "ttl": "{{ dns_zone.1.ttl | default('-1') | string }}",
        "value": "{{ dns_zone.1.value | string }}"
      }
  register: fad_dns_zone_caa_record_post_results
  loop: "{{ fad_dns_zones | subelements('caa_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.value + ' for ' + dns_zone.1.tag + ' for ' + dns_zone.0.name }}"
  when:
    - (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').mkey is undefined
  changed_when: "fad_dns_zone_caa_record_post_results.json.payload == 0"
  failed_when: "fad_dns_zone_caa_record_post_results.json.payload not in [0, -15]"

- name: Update DNS Zone CAA Record entry if it's exist and any of its value is changed.
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_dns_zone_caa_record_api_endpoint | format((dns_zone.0.name), dns_zone.1.id) }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: |
      {
        "mkey": "{{ dns_zone.1.id | string }}",
        "flag": "{{ dns_zone.1.flag | default('0') | string }}",
        "hostname": "{{ dns_zone.1.hostname | default('@') |string }}",
        "tag": "{{ dns_zone.1.tag | default('issuewild') | string }}",
        "ttl": "{{ dns_zone.1.ttl | default('-1') | string }}",
        "value": "{{ dns_zone.1.value | string }}"
      }
  register: fad_dns_zone_caa_record_put_results
  loop: "{{ fad_dns_zones | subelements('caa_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.value + ' for ' + dns_zone.1.tag + ' for ' + dns_zone.0.name }}"
  when:
    - (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').mkey is defined
    - (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').flag != dns_zone.1.flag | string or
      (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').hostname != dns_zone.1.hostname | string or
      (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').tag != dns_zone.1.tag | string or
      (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').ttl != dns_zone.1.ttl | default('-1') | string or
      (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id),validate_certs=false,
      split_lines=false, headers=fad_api_header) | from_json).get('payload').value != dns_zone.1.value | default('-1') | string
  changed_when: "fad_dns_zone_caa_record_put_results.json.payload == 0"
  failed_when: "fad_dns_zone_caa_record_put_results.json.payload not in [0, -15]"

- name: Print out the DNS Zone CAA Record values after create/update task.
  ansible.builtin.debug:
    msg: >
      {{ (lookup('url', fad_dns_zone_caa_record_api_endpoint
      % ((dns_zone.0.name), dns_zone.1.id), validate_certs=false, split_lines=false,
      headers=fad_api_header) | from_json).get('payload') }}
  loop: "{{ fad_dns_zones | subelements('caa_records') }}"
  loop_control:
    loop_var: dns_zone
    label: "{{ dns_zone.1.value + ' for ' + dns_zone.1.tag + ' for ' + dns_zone.0.name }}"
  tags: [debug]
