---

- name: Import create/update zone tasks.
  vars:
    fad_dns_zone_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone }}"
  ansible.builtin.import_tasks: fad_dns_zone.yaml
  # tagged by all child task so the parent task would also run when you tag only the child tag
  tags:
    - fad_dns_zone
    - fad_dns_zone_a_aaaa_record
    - fad_dns_zone_caa_record
    - fad_dns_zone_cname_record
    - fad_dns_zone_mx_record
    - fad_dns_zone_ns_record
    - fad_dns_zone_ptr_record
    - fad_dns_zone_srv_record
    - fad_dns_zone_txt_record

- name: Update DNS Policy zone list.
  vars:
    fad_dns_policy_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_policy }}"
  ansible.builtin.import_tasks: fad_dns_policy_zone_list_update.yaml
  tags:
    - fad_dns_zone
    - fad_dns_zone_a_aaaa_record
    - fad_dns_zone_caa_record
    - fad_dns_zone_cname_record
    - fad_dns_zone_mx_record
    - fad_dns_zone_ns_record
    - fad_dns_zone_ptr_record
    - fad_dns_zone_srv_record
    - fad_dns_zone_txt_record

- name: Import create/update A and AAAA Records tasks.
  vars:
    fad_dns_zone_a_aaaa_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_a_aaaa_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_a_aaaa_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_a_aaaa_record]

- name: Import create/update CAA Records tasks.
  vars:
    fad_dns_zone_caa_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_caa_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_caa_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_caa_record]

- name: Import create/update CNAME Records tasks.
  vars:
    fad_dns_zone_cname_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_cname_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_cname_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_cname_record]

- name: Import create/update MX Records tasks.
  vars:
    fad_dns_zone_mx_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_mx_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_mx_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_mx_record]

- name: Import create/update NS Records tasks.
  vars:
    fad_dns_zone_ns_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_ns_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_ns_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_ns_record]

- name: Import create/update PTR Records tasks.
  vars:
    fad_dns_zone_ptr_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_ptr_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_ptr_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_ptr_record]

- name: Import create/update SRV Records tasks.
  vars:
    fad_dns_zone_srv_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_srv_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_srv_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_srv_record]

- name: Import create/update TXT Records tasks.
  vars:
    fad_dns_zone_txt_record_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_zone_txt_record }}"
  ansible.builtin.import_tasks: fad_dns_zone_txt_record.yaml
  tags: [fad_dns_zone, fad_dns_zone_txt_record]
