---
# ./tasks/main.yaml

- name: Generate FortiADC global-load-balance root host to automatically create fqdn_generate zone.
  ansible.builtin.uri:
    method: POST
    url: "https://{{ ansible_host }}/api/global_load_balance_host?vdom={{ fad_vdom }}"
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
    body: |
      {
        "default-feedback-ip": "0.0.0.0",
        "default-feedback-ip6": "",
        "domain-name": "{{ item.domain_name }}.",
        "fortiview": "enable",
        "host-name": "@",
        "load-balance-method": "",
        "mkey": "{{ item.domain_scope }}_{{ item.domain_name }}",
        "persistence": "disable",
        "respond-single-record": "enable",
        "vs_pool_list": "",
        "vs_pool_list_count": ""
      }
  register: data
  delegate_to: localhost
  when: "'fortiadc' in group_names"
  changed_when: "data.json.payload == 0"
  loop: "{{ domain_entries }}"

#- name: Print out the whole response.
  #debug:
    #var: data.json

#- name: Print out the value of the payload response.
  #debug:
    #var: data.json.payload
