---

- name: Trying to create fqdn_generate zone by creating domain root record.
  ansible.builtin.include_tasks: add_glb_host_root.yaml
  loop: "{{ fad_dns_zones }}"
  loop_control:
    loop_var: dns_zone

- name: Update the zone configuration task.
  ansible.builtin.include_tasks: update_dns_zones.yaml
  loop: "{{ fad_dns_zones }}"
  loop_control:
    loop_var: dns_zone

# - name: Include the add A record DNS entry task.
#   include_tasks: add_basic_a_record.yaml
#   loop: "{{ zone_aaa_records }}"

# - name: Include the add NS record DNS entry task.
#   include_tasks: add_basic_ns_record.yaml
#   loop: "{{ zone_ns_records }}"