- name: Update the FortiADC DNS zone configuration for {{ item.name }}.
  ansible.builtin.uri:
    method: PUT
    url: "https://{{ ansible_host }}/api/global_dns_server_zone?vdom={{ fad_vdom }}&mkey=fqdn_generate_{{ item.name }}."
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
    body: |
      {
        "ttl": "{{ item.ttl }}",
        "negative_ttl": "{{ item.negative_ttl }}",
        "primary_server_ip": "{{ item.primary_ns_ip }}",
        "primary_server_name": "{{ item.primary_ns_hostname }}",
        "responsible_mail": "{{ item.responsible_mail }}"
      }
  delegate_to: localhost
  register: dns_zone_config_update_result
  failed_when: "dns_zone_config_update_result.json.payload != 0"

- name: Debug out the payload value for {{ item.name }}.
  ansible.builtin.debug:
    var: dns_zone_config_update_result.json.payload
  tags:
    - debug

- name: Get the current FortiADC DNS zone configuration for {{ item.name }}.
  ansible.builtin.uri:
    method: GET
    url: "https://{{ ansible_host }}/api/global_dns_server_zone?vdom={{ fad_vdom }}&mkey=fqdn_generate_{{ item.name }}."
    body_format: json
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      'Content-Type': 'application/json'
      'APITOKEN': '{{ fad_apitoken }}'
  delegate_to: localhost
  register: dns_zone_config_value
  tags:
    - debug

- name: Debug out the value of current FortiADC zone config for {{ item.name }}.
  ansible.builtin.debug:
    var: dns_zone_config_value.json
  tags:
    - debug